name: golangci-lint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GO: true

